# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-28 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('task_id', models.IntegerField(default=0)),
                ('parent_task_id', models.IntegerField(default=0)),
                ('prefix', models.CharField(max_length=20)),
                ('item_txt', models.CharField(max_length=2048)),
                ('doable', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_record_id', models.IntegerField(default=0)),
                ('task_id', models.IntegerField(default=0)),
                ('parent_task_id', models.IntegerField(default=0)),
                ('item_txt', models.CharField(max_length=2048)),
                ('status_cd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecordXProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_record_id', models.IntegerField(default=0)),
                ('project_id', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
