# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-31 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steeplechaser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrecordxprojectrequirement',
            old_name='user_id',
            new_name='user',
        ),
    ]
